### PR TITLE
Describe provisioning a cluster via Hive

### PR DESCRIPTION
**Pull request by srueg**
Hive installed on local Minishift, provisioning on GCP.

### CODE REVIEW

**Comment by tobru** [comment]
Any chance to `s/Minishift/CRC/` or `s/Minishift/k3s/`?

**Comment by tobru** [comment]
Aand: The `.adoc` file looks more like Markdown than Asciidoc :see_no_evil: https://asciidoctor.org/docs/asciidoc-writers-guide/ (Sorry for being picky about that)

**Comment by srueg** [comment]
> Any chance to `s/Minishift/CRC/` or `s/Minishift/k3s/`?

Unfortunately not, since the installation relies on the OpenShift specific `service.alpha.openshift.io/serving-cert-secret-name` annotation to generate certs for the admission webhook 😞

**Comment by tobru** [comment]
But `s/Minishift/CRC/` should work then? CRC = https://github.com/code-ready/crc

**Comment by srueg** [comment]
I removed the Minishift specific part and added a warning regarding plain K8s (to remove the webhooks)

**Pull request merged**
