### PR TITLE
Make Cilium the default

### PR DESCRIPTION
**Pull request by corvus-ch**
Dropped any references of Cilium being optional.

### CODE REVIEW

**Comment by megian** [comment]
There are references to OpenShift SDN and OVNKubetetes in the description. Should this be included in this PR?

**Review by simu — CHANGES_REQUESTED** [review]
Definitely needs more changes, at least switching the installer config to `networkType: Cilium` instead of patching it in the next step

**Comment by corvus-ch** [comment]
> There are references to OpenShift SDN and OVNKubetetes in the description. Should this be included in this PR?

* In the context of vSphere, OVN is still mentioned. Its about not using a certain network range when OVN is used.
* On the reference about operators, openshift-sdn is mentioned as a namespace managed by the network operators.

They both are valuable information I would not like to drop right now. I see them relevant for existing clusters still using them.

**Comment by megian** [comment]
> > There are references to OpenShift SDN and OVNKubetetes in the description. Should this be included in this PR?
> 
>     * In the context of vSphere, OVN is still mentioned. Its about not using a certain network range when OVN is used.
> 
>     * On the reference about operators, openshift-sdn is mentioned as a namespace managed by the network operators.
> 
> 
> They both are valuable information I would not like to drop right now. I see them relevant for existing clusters still using them.

Fine by me.

**Review by simu — APPROVED** [review]

**Pull request merged**
